{
  "error": "A user with this 'id' already exists."
}
